"""Creator forecast capability and private evidence-job routes."""

from __future__ import annotations

from contextlib import asynccontextmanager
import hashlib
from pathlib import Path
from typing import Any, Callable, Mapping
from uuid import UUID

from fastapi import APIRouter, File, Form, Header, HTTPException, UploadFile
from fastapi.responses import JSONResponse

from .jobs import ForecastJobAPIError, ForecastJobService
from .registry import ForecastRegistry
from .schema import build_capabilities


PRIVATE_NO_STORE_HEADERS = {
    "Cache-Control": "private, no-store",
    "Pragma": "no-cache",
    "X-Content-Type-Options": "nosniff",
}

FORECAST_RUNTIME_BRANCH_KEYS = (
    "vjepa21",
    "videoLlama21Av",
    "audioModel",
    "semanticModel",
    "measuredAudio",
)
PUBLIC_ADAPTER_STATUS_KEYS = frozenset(
    {
        "role",
        "usesLearnedModel",
        "isBehavioralModel",
        "isSpeechTranscript",
        "isVideoLlama",
        "usesAudio",
        "isAudioModel",
        "provenance",
    }
)


def _adapter_runtime_status(adapter: Any) -> dict[str, Any]:
    """Inspect cheap local readiness without loading a model or making network calls."""

    class_name = type(adapter).__name__
    # Local V-JEPA readiness instantiates/verifies a large checkpoint and HTTP
    # adapter readiness contacts another service. Both belong to job execution,
    # never to a lightweight status request.
    deferred = class_name == "LocalVJepa21Adapter" or (
        callable(getattr(adapter, "probe", None))
        and not callable(getattr(adapter, "availability", None))
    )
    if deferred or not callable(getattr(adapter, "availability", None)):
        return {
            "configured": True,
            "executionAvailable": None,
            "readinessDeferred": True,
            "executionScope": (
                "configured-http-worker"
                if callable(getattr(adapter, "probe", None))
                else "in-process-local-worker"
            ),
            "reason": "Readiness and immutable provenance are verified inside each job so the status route never loads a model or contacts a remote worker.",
            "readinessDiagnostics": [
                "An executable adapter is configured.",
                "Per-job readiness remains fail-closed until the adapter validates itself.",
            ],
        }
    try:
        value = adapter.availability()
    except Exception:
        return {
            "configured": True,
            "executionAvailable": False,
            "readinessDeferred": False,
            "executionScope": "in-process-local-worker",
            "reason": "The configured local adapter failed its non-destructive readiness check.",
            "readinessDiagnostics": ["No model output was generated by this status check."],
        }
    if not isinstance(value, Mapping):
        return {
            "configured": True,
            "executionAvailable": False,
            "readinessDeferred": False,
            "executionScope": "in-process-local-worker",
            "reason": "The configured local adapter returned an invalid readiness document.",
            "readinessDiagnostics": ["No model output was generated by this status check."],
        }
    configured = value.get("configured") is True
    execution_available = value.get("executionAvailable") is True
    provider = {
        key: item
        for key, item in value.items()
        if key in PUBLIC_ADAPTER_STATUS_KEYS
    }
    return {
        "configured": configured,
        "executionAvailable": execution_available,
        "readinessDeferred": False,
        "executionScope": "in-process-local-worker",
        "reason": value.get("reason") if isinstance(value.get("reason"), str) else None,
        "provider": provider,
        "readinessDiagnostics": [
            "Readiness used only filesystem, executable, and installed-runtime checks.",
            "No media inference or behavioral scoring ran for this status response.",
        ],
    }


def _forecast_job_runtime_status(job_service: ForecastJobService) -> dict[str, Any]:
    orchestrator = job_service.orchestrator
    raw_adapters = getattr(orchestrator, "adapters", {})
    adapters = raw_adapters if isinstance(raw_adapters, Mapping) else {}
    raw_head_runtime = getattr(orchestrator, "head_runtime", None)
    raw_heads = getattr(raw_head_runtime, "heads", {})
    heads = raw_heads if isinstance(raw_heads, Mapping) else {}
    return {
        "branches": {
            key: _adapter_runtime_status(adapters[key])
            for key in FORECAST_RUNTIME_BRANCH_KEYS
            if key in adapters
        },
        "executableHeadKeys": sorted(
            key for key in heads if isinstance(key, str)
        ),
    }


def _browser_analysis_sha256() -> str | None:
    path = Path(__file__).resolve().parents[2] / "src" / "analysis.js"
    if not path.is_file():
        return None
    digest = hashlib.sha256()
    try:
        with path.open("rb") as handle:
            while chunk := handle.read(1024 * 1024):
                digest.update(chunk)
    except OSError:
        return None
    return digest.hexdigest()


def create_forecast_router(
    *,
    tribe_status_provider: Callable[[], dict[str, Any]],
    registry: ForecastRegistry | None = None,
    job_service: ForecastJobService | None = None,
) -> APIRouter:
    # Invalid configured artifacts stop app construction. An absent registry is
    # valid and yields explicit not-configured states for optional providers.
    active_registry = registry if registry is not None else ForecastRegistry.from_env()
    active_jobs = job_service if job_service is not None else ForecastJobService.from_env()
    browser_source_sha256 = _browser_analysis_sha256()

    @asynccontextmanager
    async def lifespan(_: Any):
        await active_jobs.startup()
        try:
            yield
        finally:
            await active_jobs.shutdown()

    router = APIRouter(
        prefix="/api/forecast/v1",
        tags=["creator-forecast"],
        lifespan=lifespan,
    )

    def raise_job_error(exc: ForecastJobAPIError) -> None:
        raise HTTPException(
            status_code=exc.status_code,
            detail={"code": exc.code, "message": exc.message},
            headers=PRIVATE_NO_STORE_HEADERS,
        ) from exc

    @router.get("/status")
    def forecast_status() -> JSONResponse:
        try:
            tribe_status: Any = tribe_status_provider()
        except Exception:
            tribe_status = None
        return JSONResponse(
            build_capabilities(
                active_registry,
                tribe_runtime_status=tribe_status,
                browser_analysis_source_sha256=browser_source_sha256,
                forecast_job_runtime_status=_forecast_job_runtime_status(active_jobs),
            ),
            headers={
                "Cache-Control": "no-store",
                "X-Content-Type-Options": "nosniff",
            },
        )

    @router.post("/jobs", status_code=202)
    async def create_forecast_job(
        video: UploadFile = File(...),
        context: str | None = Form(default=None),
        idempotency_key: str | None = Header(default=None, alias="Idempotency-Key"),
    ) -> JSONResponse:
        try:
            job = await active_jobs.submit(video, context, idempotency_key)
        except ForecastJobAPIError as exc:
            raise_job_error(exc)
        return JSONResponse(
            job,
            status_code=202,
            headers={
                **PRIVATE_NO_STORE_HEADERS,
                "Location": job["links"]["self"],
                "Retry-After": "1",
                **(
                    {"Idempotency-Key": job["jobId"]}
                    if idempotency_key is not None
                    else {}
                ),
            },
        )

    @router.get("/jobs/{job_id}")
    async def get_forecast_job(job_id: UUID) -> JSONResponse:
        try:
            job = await active_jobs.get_job(job_id)
        except ForecastJobAPIError as exc:
            raise_job_error(exc)
        return JSONResponse(job, headers=PRIVATE_NO_STORE_HEADERS)

    @router.get("/results/{result_id}")
    async def get_forecast_result(result_id: UUID) -> JSONResponse:
        try:
            result = await active_jobs.get_result(result_id)
        except ForecastJobAPIError as exc:
            raise_job_error(exc)
        return JSONResponse(result, headers=PRIVATE_NO_STORE_HEADERS)

    return router
